import { Global, Module } from '@nestjs/common';
import { MongooseModule, ModelDefinition } from '@nestjs/mongoose';
import {
  User,
  UserSchema,
  Folder,
  FolderSchema,
  FileItem,
  FileItemSchema,
  Download,
  DownloadSchema,
  Topic,
  TopicSchema,
  Question,
  QuestionSchema,
  SingleChoiceQuestion,
  SingleChoiceQuestionSchema,
  MultipleChoiceQuestion,
  MultipleChoiceQuestionSchema,
  TrueFalseQuestion,
  TrueFalseQuestionSchema,
  ShortAnswerQuestion,
  ShortAnswerQuestionSchema,
  EssayQuestion,
  EssayQuestionSchema,
  MatchQuestion,
  MatchQuestionSchema,
  NumberQuestion,
  NumberQuestionSchema,
  SortQuestion,
  SortQuestionSchema,
  TableSelectionQuestion,
  TableSelectionQuestionSchema,
  RubricGroup,
  RubricGroupSchema,
  Rubric,
  RubricSchema,
  RubricLevel,
  RubricLevelSchema,
  RubricCriterion,
  RubricCriterionSchema,
  Exercise,
  ExerciseSchema,
  ExerciseFolder,
  ExerciseFolderSchema,
  ExerciseQuestion,
  ExerciseQuestionSchema,
  Attempt,
  AttemptSchema,
  Participant,
  ParticipantSchema,
  Submission,
  SubmissionSchema,
  StudentQuestion,
  StudentQuestionSchema,
  SelfAssessment,
  SelfAssessmentSchema,
  Article,
  ArticleSchema,
  Notification,
  NotificationSchema,
  Settings,
  SettingsSchema,
  Schedule,
  ScheduleSchema,
} from '../schemas';

// Model name (X.name) is what `ref`/`refPath` point to, so registering with
// `name: X.name` keeps every relation (and the polymorphic questionModel) resolvable.
const MODELS: ModelDefinition[] = [
  { name: User.name, schema: UserSchema },
  { name: Folder.name, schema: FolderSchema },
  { name: FileItem.name, schema: FileItemSchema },
  { name: Download.name, schema: DownloadSchema },
  { name: Topic.name, schema: TopicSchema },
  { name: Question.name, schema: QuestionSchema },
  { name: SingleChoiceQuestion.name, schema: SingleChoiceQuestionSchema },
  { name: MultipleChoiceQuestion.name, schema: MultipleChoiceQuestionSchema },
  { name: TrueFalseQuestion.name, schema: TrueFalseQuestionSchema },
  { name: ShortAnswerQuestion.name, schema: ShortAnswerQuestionSchema },
  { name: EssayQuestion.name, schema: EssayQuestionSchema },
  { name: MatchQuestion.name, schema: MatchQuestionSchema },
  { name: NumberQuestion.name, schema: NumberQuestionSchema },
  { name: SortQuestion.name, schema: SortQuestionSchema },
  { name: TableSelectionQuestion.name, schema: TableSelectionQuestionSchema },
  { name: RubricGroup.name, schema: RubricGroupSchema },
  { name: Rubric.name, schema: RubricSchema },
  { name: RubricLevel.name, schema: RubricLevelSchema },
  { name: RubricCriterion.name, schema: RubricCriterionSchema },
  { name: Exercise.name, schema: ExerciseSchema },
  { name: ExerciseFolder.name, schema: ExerciseFolderSchema },
  { name: ExerciseQuestion.name, schema: ExerciseQuestionSchema },
  { name: Attempt.name, schema: AttemptSchema },
  { name: Participant.name, schema: ParticipantSchema },
  { name: Submission.name, schema: SubmissionSchema },
  { name: StudentQuestion.name, schema: StudentQuestionSchema },
  { name: SelfAssessment.name, schema: SelfAssessmentSchema },
  { name: Article.name, schema: ArticleSchema },
  { name: Notification.name, schema: NotificationSchema },
  { name: Settings.name, schema: SettingsSchema },
  { name: Schedule.name, schema: ScheduleSchema },
];

@Global()
@Module({
  imports: [MongooseModule.forFeature(MODELS)],
  exports: [MongooseModule],
})
export class DatabaseModule {}
